- hosts: mgmt
  gather_facts: 'no'
  vars_files:
    - vars/vars.yaml
  tasks:
    - name: Install required packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - curl
          - tinyproxy
        state: present
        update_cache: yes
        cache_valid_time: 86400
      become: true
      become_user: root

    #tinyproxy
    - block:
        - name: Check if logfile exists.
          ansible.builtin.stat:
            path: '/var/log/tinyproxy/tinyproxy.log'
          register: logfile_status

        - name: Check for Allow localhost rule
          lineinfile:
            path: /etc/tinyproxy/tinyproxy.conf
            line: Allow localhost
            regexp: '^Allow localhost$' # Only modify if line doesn't exist
            insertafter: EOF
            state: present
          register: allow_localhost

        - name: Create tinyproxy log file
          file:
            path: /var/log/tinyproxy/tinyproxy.log
            state: touch
            mode: '0744'
            owner: tinyproxy
            group: tinyproxy
          register: create_logfile
          when: not logfile_status.stat.exists

        - name: Restart tinyproxy
          service:
            name: tinyproxy
            state: restarted
          when: allow_localhost.changed or create_logfile.changed
      become: true
      become_user: root
