apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{include "router.fullname" .}}-frontend-config
spec:
  sslPolicy: {{ .Values.sslPolicy}}
  redirectToHttps:
    enabled: true
