---
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "router.secretName" . }}
  annotations:
    # Support for k14s.io. This annotation will produce a redeployment when the secret changes.
    kapp.k14s.io/versioned: ""
  labels:
    {{- include "router.labels" . | nindent 4 }}
data:
  graphApiToken: {{ .Values.configuration.graphApiToken | b64enc | quote }}
{{- end }}
